<?php

namespace Database\Seeders;

use App\Models\Odp;
use App\Models\Olt;
use Illuminate\Database\Seeder;

class OdpSeeder extends Seeder
{
    public function run(): void
    {
        $oltServer = Olt::where('name', 'like', '%SERVER%')->first() ?? Olt::first();
        $oltBandarDalam = Olt::where('name', 'like', '%BANDAR DALAM%')->first() ?? Olt::first();
        $oltSidomulyo = Olt::where('name', 'like', '%SIDOMULYO%')->first() ?? Olt::first();
        $oltBabatan = Olt::where('name', 'like', '%BABATAN%')->first() ?? Olt::first();
        $oltTarahan = Olt::where('name', 'like', '%TARAHAN%')->first() ?? Olt::first();
        $oltSukabanjar = Olt::where('name', 'like', '%SUKABANJAR%')->first() ?? Olt::first();

        $odps = [
            // SCENARIO 1: ODP 1 Lokasi Sidodadi - 8 Pelanggan, 1 Mati Kabel Fiber Cut
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-01/POP-SVR',
                'kode_odp'            => 'ODP-01',
                'lokasi'              => 'Sidodadi Gg. Mawar 1',
                'pon_port'            => 1,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 7,
                'offline_pelanggan'   => 1,
                'status'              => 'fiber_cut',
                'keterangan_gangguan' => '🔴 1 Pelanggan (Ibu Rina - Port 4) LOS Kabel Fiber Cut Putus Tertimpa Ranting',
                'parent_odc'          => 'SERVER UTAMA',
                'latitude'            => -5.452400,
                'longitude'           => 105.271100,
                'ports_data'          => [
                    ['port' => 1, 'nama' => 'Bpk. Hendra', 'status' => 'online', 'rx' => '-19.2 dBm', 'reason' => 'Normal'],
                    ['port' => 2, 'nama' => 'Bpk. Joko', 'status' => 'online', 'rx' => '-20.1 dBm', 'reason' => 'Normal'],
                    ['port' => 3, 'nama' => 'Ibu Siti', 'status' => 'online', 'rx' => '-18.7 dBm', 'reason' => 'Normal'],
                    ['port' => 4, 'nama' => 'Ibu Rina', 'status' => 'offline', 'rx' => '-40.0 dBm', 'reason' => 'LOS / Kabel Fiber Cut'],
                    ['port' => 5, 'nama' => 'Bpk. Dedi', 'status' => 'online', 'rx' => '-19.8 dBm', 'reason' => 'Normal'],
                    ['port' => 6, 'nama' => 'Toko Berkah', 'status' => 'online', 'rx' => '-21.3 dBm', 'reason' => 'Normal'],
                    ['port' => 7, 'nama' => 'Bpk. Slamet', 'status' => 'online', 'rx' => '-19.5 dBm', 'reason' => 'Normal'],
                    ['port' => 8, 'nama' => 'Bpk. Agus', 'status' => 'online', 'rx' => '-20.4 dBm', 'reason' => 'Normal'],
                ],
                'notes'               => 'Tiang Telkom No. 12 Depan Pos Ronda',
            ],

            // SCENARIO 2: ODP 2 Sidodadi - Adaptor Dicabut Pelanggan
            [
                'olt_id'              => $oltSidomulyo ? $oltSidomulyo->id : null,
                'nama_odp'            => 'EO/ODP-02/SDM-ODC-02',
                'kode_odp'            => 'ODP-02',
                'lokasi'              => 'Sidodadi Timur RT 03',
                'pon_port'            => 2,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 7,
                'offline_pelanggan'   => 1,
                'status'              => 'power_off',
                'keterangan_gangguan' => '🟡 1 Pelanggan (Bpk. Wahyu - Port 2) Adaptor Dicabut / Dying Gasp',
                'parent_odc'          => 'SDM-ODC-02',
                'latitude'            => -5.535800,
                'longitude'           => 105.354200,
                'ports_data'          => [
                    ['port' => 1, 'nama' => 'Bpk. Anton', 'status' => 'online', 'rx' => '-19.0 dBm', 'reason' => 'Normal'],
                    ['port' => 2, 'nama' => 'Bpk. Wahyu', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Dying Gasp / Adaptor Dicabut'],
                    ['port' => 3, 'nama' => 'Ibu Wati', 'status' => 'online', 'rx' => '-20.2 dBm', 'reason' => 'Normal'],
                    ['port' => 4, 'nama' => 'Bpk. Doni', 'status' => 'online', 'rx' => '-18.5 dBm', 'reason' => 'Normal'],
                    ['port' => 5, 'nama' => 'Bpk. Herman', 'status' => 'online', 'rx' => '-21.0 dBm', 'reason' => 'Normal'],
                    ['port' => 6, 'nama' => 'Ibu Yuli', 'status' => 'online', 'rx' => '-19.4 dBm', 'reason' => 'Normal'],
                    ['port' => 7, 'nama' => 'Bpk. Ilham', 'status' => 'online', 'rx' => '-20.1 dBm', 'reason' => 'Normal'],
                    ['port' => 8, 'nama' => 'Ibu Ratna', 'status' => 'online', 'rx' => '-19.7 dBm', 'reason' => 'Normal'],
                ],
                'notes'               => 'Tiang Besi EONET No. 04',
            ],

            // SCENARIO 3: ODP 3 Bandar Dalam - Mati Lampu PLN Area
            [
                'olt_id'              => $oltBandarDalam ? $oltBandarDalam->id : null,
                'nama_odp'            => 'EO/ODP-03/POP-SVR',
                'kode_odp'            => 'ODP-03',
                'lokasi'              => 'Bandar Dalam Pasar',
                'pon_port'            => 1,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 0,
                'offline_pelanggan'   => 8,
                'status'              => 'mati_lampu',
                'keterangan_gangguan' => '⚡ Seluruh 8 ONU Mati Bersamaan (Mati Lampu PLN Padam Area Bandar Dalam)',
                'parent_odc'          => 'SERVER UTAMA',
                'latitude'            => -5.516500,
                'longitude'           => 105.322800,
                'ports_data'          => [
                    ['port' => 1, 'nama' => 'Toko Makmur', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 2, 'nama' => 'Bpk. Bambang', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 3, 'nama' => 'Ibu Sri', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 4, 'nama' => 'Klinik Sehat', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 5, 'nama' => 'Bpk. Rudi', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 6, 'nama' => 'Fotocopy Cepat', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 7, 'nama' => 'Bpk. Lukman', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                    ['port' => 8, 'nama' => 'Ibu Ningsih', 'status' => 'offline', 'rx' => '-35.0 dBm', 'reason' => 'Mati Lampu PLN'],
                ],
                'notes'               => 'Tiang PLN Pasar Bandar Dalam',
            ],

            // MORE REAL ODPS FROM GOOGLE EARTH SCREENSHOT
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-04/POP-SVR',
                'kode_odp'            => 'ODP-04',
                'lokasi'              => 'Server NOC Utama Belakang',
                'pon_port'            => 1,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 8,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Semua Pelanggan Normal (-18.8 dBm)',
                'parent_odc'          => 'SERVER UTAMA',
                'latitude'            => -5.450200,
                'longitude'           => 105.267500,
                'notes'               => 'Tiang Utama 01',
            ],
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-05/POP-SVR',
                'kode_odp'            => 'ODP-05',
                'lokasi'              => 'Server NOC Timur',
                'pon_port'            => 2,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 8,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Semua Pelanggan Normal (-19.3 dBm)',
                'parent_odc'          => 'SERVER UTAMA',
                'latitude'            => -5.451800,
                'longitude'           => 105.269200,
                'notes'               => 'Tiang Utama 02',
            ],
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-06-GGSOSIAL/ODC 1 SIDORUKUN',
                'kode_odp'            => 'ODP-06-GS',
                'lokasi'              => 'Gg. Sosial Sidorukun',
                'pon_port'            => 3,
                'kapasitas'           => 16,
                'total_pelanggan'     => 14,
                'online_pelanggan'    => 14,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-19.1 dBm)',
                'parent_odc'          => 'ODC 1 SIDORUKUN',
                'latitude'            => -5.454200,
                'longitude'           => 105.272500,
                'notes'               => 'Tiang ODC Sidorukun',
            ],
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-07-GGSOSIAL/ODC 1 SIDORUKUN',
                'kode_odp'            => 'ODP-07-GS',
                'lokasi'              => 'Gg. Sosial Tengah Sidorukun',
                'pon_port'            => 3,
                'kapasitas'           => 16,
                'total_pelanggan'     => 12,
                'online_pelanggan'    => 12,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-19.6 dBm)',
                'parent_odc'          => 'ODC 1 SIDORUKUN',
                'latitude'            => -5.455100,
                'longitude'           => 105.273800,
                'notes'               => 'Tiang Gg. Sosial 03',
            ],
            [
                'olt_id'              => $oltServer ? $oltServer->id : null,
                'nama_odp'            => 'EO/ODP-08-GGSOSIAL/ODC 1 SIDORUKUN',
                'kode_odp'            => 'ODP-08-GS',
                'lokasi'              => 'Gg. Sosial Ujung Sidorukun',
                'pon_port'            => 4,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 8,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-20.0 dBm)',
                'parent_odc'          => 'ODC 1 SIDORUKUN',
                'latitude'            => -5.456300,
                'longitude'           => 105.275000,
                'notes'               => 'Tiang Gg. Sosial 05',
            ],
            [
                'olt_id'              => $oltSidomulyo ? $oltSidomulyo->id : null,
                'nama_odp'            => 'EO/ODP-03/SDM-ODC-02',
                'kode_odp'            => 'ODP-03-SDM',
                'lokasi'              => 'Sidomulyo Pasar',
                'pon_port'            => 3,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 8,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-18.9 dBm)',
                'parent_odc'          => 'SDM-ODC-02',
                'latitude'            => -5.534800,
                'longitude'           => 105.352800,
                'notes'               => 'Tiang Pasar Sidomulyo',
            ],
            [
                'olt_id'              => $oltBabatan ? $oltBabatan->id : null,
                'nama_odp'            => 'EO/BML-ODP-12/PST-SVR',
                'kode_odp'            => 'ODP-12-BBT',
                'lokasi'              => 'Babatan Raya Simpang',
                'pon_port'            => 1,
                'kapasitas'           => 16,
                'total_pelanggan'     => 15,
                'online_pelanggan'    => 15,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-19.2 dBm)',
                'parent_odc'          => 'CLOSUR KOTAK 1',
                'latitude'            => -5.512900,
                'longitude'           => 105.319200,
                'notes'               => 'Tiang Simpang Babatan',
            ],
            [
                'olt_id'              => $oltTarahan ? $oltTarahan->id : null,
                'nama_odp'            => 'EO/BML-ODP-13/POP-SVR',
                'kode_odp'            => 'ODP-13-TRH',
                'lokasi'              => 'Tarahan Pelabuhan',
                'pon_port'            => 2,
                'kapasitas'           => 16,
                'total_pelanggan'     => 14,
                'online_pelanggan'    => 14,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-19.8 dBm)',
                'parent_odc'          => 'CLOSUR 4C',
                'latitude'            => -5.521800,
                'longitude'           => 105.311900,
                'notes'               => 'Tiang Depan Pelabuhan',
            ],
            [
                'olt_id'              => $oltSukabanjar ? $oltSukabanjar->id : null,
                'nama_odp'            => 'EO/KDG-ODC-01/POP-SVR',
                'kode_odp'            => 'ODP-01-SKB',
                'lokasi'              => 'Sukabanjar Balai Desa',
                'pon_port'            => 4,
                'kapasitas'           => 8,
                'total_pelanggan'     => 8,
                'online_pelanggan'    => 8,
                'offline_pelanggan'   => 0,
                'status'              => 'normal',
                'keterangan_gangguan' => '🟢 Normal (-19.5 dBm)',
                'parent_odc'          => 'KDG-ODC-01',
                'latitude'            => -5.503100,
                'longitude'           => 105.306800,
                'notes'               => 'Tiang Balai Desa Sukabanjar',
            ],
        ];

        foreach ($odps as $item) {
            Odp::updateOrCreate(
                ['nama_odp' => $item['nama_odp']],
                $item
            );
        }
    }
}
