<?php

namespace Database\Seeders;

use App\Models\Olt;
use Illuminate\Database\Seeder;

class OltSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $olts = [
            // ============================================================
            // 1-5: 5 UNIT OLT HSGQ 8 PON EPON
            // ============================================================
            [
                'name'          => 'OLT HSGQ 8P EPON - Pusat NOC',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.11',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Pusat / NOC Didi',
                'latitude'      => -5.448500,
                'longitude'     => 105.266500,
                'status'        => 'online',
                'temperature'   => 41.2,
                'cpu_usage'     => 18,
                'ram_usage'     => 38,
                'voltage'       => 12.2,
                'total_onu'     => 192,
                'online_onu'    => 184,
                'offline_onu'   => 8,
                'notes'         => 'OLT Backbone Utama Area Pusat',
            ],
            [
                'name'          => 'OLT HSGQ 8P EPON - Babatan 1',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.12',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Babatan Rack 1',
                'latitude'      => -5.512200,
                'longitude'     => 105.318400,
                'status'        => 'online',
                'temperature'   => 43.5,
                'cpu_usage'     => 22,
                'ram_usage'     => 42,
                'voltage'       => 12.1,
                'total_onu'     => 168,
                'online_onu'    => 159,
                'offline_onu'   => 9,
                'notes'         => 'Coverage Babatan Timur & Pasar',
            ],
            [
                'name'          => 'OLT HSGQ 8P EPON - Tarahan 1',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.13',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Tarahan Rack 1',
                'latitude'      => -5.539800,
                'longitude'     => 105.347500,
                'status'        => 'online',
                'temperature'   => 42.0,
                'cpu_usage'     => 15,
                'ram_usage'     => 36,
                'voltage'       => 12.3,
                'total_onu'     => 144,
                'online_onu'    => 138,
                'offline_onu'   => 6,
                'notes'         => 'Coverage Kawasan Industri Tarahan',
            ],
            [
                'name'          => 'OLT HSGQ 8P EPON - Sukabanjar',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.14',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Sukabanjar',
                'latitude'      => -5.487000,
                'longitude'     => 105.289000,
                'status'        => 'online',
                'temperature'   => 44.1,
                'cpu_usage'     => 20,
                'ram_usage'     => 40,
                'voltage'       => 12.0,
                'total_onu'     => 120,
                'online_onu'    => 114,
                'offline_onu'   => 6,
                'notes'         => 'Coverage Sukabanjar & Sekitarnya',
            ],
            [
                'name'          => 'OLT HSGQ 8P EPON - Taman Agung 1',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.15',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Taman Agung',
                'latitude'      => -5.465000,
                'longitude'     => 105.275000,
                'status'        => 'online',
                'temperature'   => 40.8,
                'cpu_usage'     => 17,
                'ram_usage'     => 35,
                'voltage'       => 12.2,
                'total_onu'     => 156,
                'online_onu'    => 149,
                'offline_onu'   => 7,
                'notes'         => 'Coverage Perumahan Taman Agung',
            ],

            // ============================================================
            // 6-10: 5 UNIT OLT HSGQ 4 PON EPON
            // ============================================================
            [
                'name'          => 'OLT HSGQ 4P EPON - Babatan 2',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.21',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Babatan Rack 2',
                'latitude'      => -5.515000,
                'longitude'     => 105.321000,
                'status'        => 'online',
                'temperature'   => 39.5,
                'cpu_usage'     => 12,
                'ram_usage'     => 30,
                'voltage'       => 12.1,
                'total_onu'     => 84,
                'online_onu'    => 80,
                'offline_onu'   => 4,
                'notes'         => 'Distribusi Babatan Barat',
            ],
            [
                'name'          => 'OLT HSGQ 4P EPON - Tarahan 2',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.22',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Tarahan Rack 2',
                'latitude'      => -5.542000,
                'longitude'     => 105.351000,
                'status'        => 'online',
                'temperature'   => 41.0,
                'cpu_usage'     => 14,
                'ram_usage'     => 32,
                'voltage'       => 12.2,
                'total_onu'     => 72,
                'online_onu'    => 68,
                'offline_onu'   => 4,
                'notes'         => 'Tarahan Pesisir',
            ],
            [
                'name'          => 'OLT HSGQ 4P EPON - Katibung',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.23',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Katibung',
                'latitude'      => -5.568000,
                'longitude'     => 105.385000,
                'status'        => 'warning',
                'temperature'   => 48.2, // Higher temp indicator
                'cpu_usage'     => 28,
                'ram_usage'     => 45,
                'voltage'       => 11.9,
                'total_onu'     => 96,
                'online_onu'    => 86,
                'offline_onu'   => 10,
                'notes'         => 'POP Katibung Tengah (Suhu agak tinggi)',
            ],
            [
                'name'          => 'OLT HSGQ 4P EPON - Merak Belantung',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.24',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Merak Belantung',
                'latitude'      => -5.612000,
                'longitude'     => 105.465000,
                'status'        => 'online',
                'temperature'   => 38.8,
                'cpu_usage'     => 11,
                'ram_usage'     => 28,
                'voltage'       => 12.3,
                'total_onu'     => 60,
                'online_onu'    => 58,
                'offline_onu'   => 2,
                'notes'         => 'Kawasan Wisata Pantai Merak Belantung',
            ],
            [
                'name'          => 'OLT HSGQ 4P EPON - Kalianda Utara',
                'brand'         => 'HSGQ',
                'type'          => 'EPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.25',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Kalianda Utara',
                'latitude'      => -5.685000,
                'longitude'     => 105.578000,
                'status'        => 'online',
                'temperature'   => 40.2,
                'cpu_usage'     => 16,
                'ram_usage'     => 34,
                'voltage'       => 12.1,
                'total_onu'     => 78,
                'online_onu'    => 73,
                'offline_onu'   => 5,
                'notes'         => 'Perbatasan Masuk Kalianda',
            ],

            // ============================================================
            // 11-13: 3 UNIT OLT HSGQ 8 PON GPON
            // ============================================================
            [
                'name'          => 'OLT HSGQ 8P GPON - Pusat',
                'brand'         => 'HSGQ',
                'type'          => 'GPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.31',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Pusat GPON Bay',
                'latitude'      => -5.449000,
                'longitude'     => 105.268000,
                'status'        => 'online',
                'temperature'   => 43.8,
                'cpu_usage'     => 24,
                'ram_usage'     => 45,
                'voltage'       => 12.2,
                'total_onu'     => 256,
                'online_onu'    => 248,
                'offline_onu'   => 8,
                'notes'         => 'GPON Kecepatan Tinggi Pelanggan Dedicated & Bisnis',
            ],
            [
                'name'          => 'OLT HSGQ 8P GPON - Babatan',
                'brand'         => 'HSGQ',
                'type'          => 'GPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.32',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Babatan GPON Bay',
                'latitude'      => -5.513000,
                'longitude'     => 105.319500,
                'status'        => 'online',
                'temperature'   => 42.6,
                'cpu_usage'     => 19,
                'ram_usage'     => 41,
                'voltage'       => 12.1,
                'total_onu'     => 210,
                'online_onu'    => 202,
                'offline_onu'   => 8,
                'notes'         => 'GPON Residential Babatan',
            ],
            [
                'name'          => 'OLT HSGQ 8P GPON - Tarahan',
                'brand'         => 'HSGQ',
                'type'          => 'GPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.33',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'admin123',
                'location_name' => 'POP Tarahan GPON Bay',
                'latitude'      => -5.541000,
                'longitude'     => 105.349000,
                'status'        => 'online',
                'temperature'   => 41.9,
                'cpu_usage'     => 18,
                'ram_usage'     => 39,
                'voltage'       => 12.2,
                'total_onu'     => 180,
                'online_onu'    => 174,
                'offline_onu'   => 6,
                'notes'         => 'GPON Industri & Pelabuhan Tarahan',
            ],

            // ============================================================
            // 14: 1 UNIT OLT GLOBAL GPON 4 PON
            // ============================================================
            [
                'name'          => 'OLT Global 4P GPON - Kalianda',
                'brand'         => 'Global',
                'type'          => 'GPON',
                'pon_ports'     => 4,
                'ip_address'    => '192.168.20.41',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'global123',
                'location_name' => 'POP Kalianda Kota',
                'latitude'      => -5.722000,
                'longitude'     => 105.592000,
                'status'        => 'online',
                'temperature'   => 39.1,
                'cpu_usage'     => 14,
                'ram_usage'     => 31,
                'voltage'       => 12.4,
                'total_onu'     => 94,
                'online_onu'    => 90,
                'offline_onu'   => 4,
                'notes'         => 'Global Technology OLT 4 PON GPON Kalianda Sentra',
            ],

            // ============================================================
            // 15: 1 UNIT OLT GLOBAL 8 PON EPON
            // ============================================================
            [
                'name'          => 'OLT Global 8P EPON - Sidomulyo',
                'brand'         => 'Global',
                'type'          => 'EPON',
                'pon_ports'     => 8,
                'ip_address'    => '192.168.20.51',
                'snmp_port'     => 161,
                'snmp_community'=> 'public',
                'telnet_port'   => 23,
                'web_port'      => 80,
                'username'      => 'admin',
                'password'      => 'global123',
                'location_name' => 'POP Sidomulyo',
                'latitude'      => -5.589000,
                'longitude'     => 105.525000,
                'status'        => 'online',
                'temperature'   => 42.3,
                'cpu_usage'     => 21,
                'ram_usage'     => 43,
                'voltage'       => 12.0,
                'total_onu'     => 160,
                'online_onu'    => 151,
                'offline_onu'   => 9,
                'notes'         => 'Global Technology OLT 8 PON EPON Area Sidomulyo',
            ],
        ];

        foreach ($olts as $oltData) {
            $ponData = Olt::generateDefaultPonData(
                $oltData['type'],
                $oltData['pon_ports'],
                $oltData['total_onu']
            );

            Olt::updateOrCreate(
                ['ip_address' => $oltData['ip_address']],
                array_merge($oltData, ['pon_data' => $ponData])
            );
        }
    }
}
